baseURL = "https://emlautarom1.github.io/"
languageCode = "en-us"
title = "(Î») Lambda Prime"
theme = 'tale'
enableEmoji = true
publishDir = "public"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[author]
  name = "Lautaro Emanuel"

[params]
  css = ["custom.css"]

[markup]
  [markup.highlight]
    lineNos = false
    style = 'onedark'
